use_frameworks!

platform :ios, '13.5'

target 'iosApp' do
    pod 'cocoapodsshared', git: "https://github.com/satoshun-android-example/KMMExternalSourceCocoapods.git"

    pod 'AFNetworking', '~> 4.0'
end
